server:
  port: 8090

logging:
  level:
    com:
      eazybytes:
        loan: DEBUG

spring:
  application:
    name: loans

  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/easy-microservice-loan

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8071/"

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true # to check health of the service if its down then its won't receive traffic
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
